// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationApp.DALLibrary.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationApp.DALLibrary.Migrations
{
    [DbContext(typeof(NotificationAppContext))]
    [Migration("20260514072505_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationApp.ModelLibrary.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsertoNotify")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsertoNotify");

                    b.ToTable("notifications");

                    b.HasDiscriminator<int>("NotificationType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NotificationApp.ModelLibrary.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("NotificationApp.ModelLibrary.Models.EmailNotification", b =>
                {
                    b.HasBaseType("NotificationApp.ModelLibrary.Models.Notification");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("NotificationApp.ModelLibrary.Models.SMSNotification", b =>
                {
                    b.HasBaseType("NotificationApp.ModelLibrary.Models.Notification");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("NotificationApp.ModelLibrary.Models.Notification", b =>
                {
                    b.HasOne("NotificationApp.ModelLibrary.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UsertoNotify")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Notification_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotificationApp.ModelLibrary.Models.User", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
